#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

# Get the full path of the repo
GIT_PATH=$(git rev-parse --show-toplevel)

# Run the trello_commit script with the git path
cykle trello link-commit "$(git log -1 --oneline HEAD)"
